version: '2'
services:
    consul:
        image: consul:0.9.3
        ports:
            - 8500:8500
        command: consul agent -dev -ui -client 0.0.0.0 -log-level err

    consul-config-loader:
        image: jhipster/consul-config-loader:v0.2.2
        volumes:
            - ./central-server-config:/config
        environment:
            - INIT_SLEEP_SECONDS=10
            - CONSUL_URL=consul
            - CONSUL_PORT=8500

    uaa-mysql:
        image: mysql:5.7.20
        volumes:
            - ~/database/ucumos/uaa/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=uaa
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

    umm-mysql:
        image: mysql:5.7.20
        volumes:
            - ~/database/ucumos/umm/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=umm
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

    uface-mysql:
        image: mysql:5.7.20
        volumes:
            - ~/database/ucumos/uface/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=uface
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

    uaapy-app:
        image: uaapy
        environment:
            - START_SLEEP=20

    ummpy-app:
        image: ummpy
        environment:
            - START_SLEEP=50

    umupy-app:
        image: umupy
        privileged: true  # remove while deploy in k8s
        volumes:  # remove volumes mapping  while deploy in k8s
            - /usr/bin/docker:/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DOCKER_LOCATION=local  # change to 'remote' while deploy in k8s
            - START_SLEEP=50

    umdpy-app:
        image: umdpy
        environment:
            - START_SLEEP=50

    abilitypy-app:
        image: abilitypy
        environment:
            - START_SLEEP=50

    portalpy-app:
        image: portalpy
        environment:
            - START_SLEEP=30

    ppersonalpy-app:
        image: ppersonalpy
        environment:
            - START_SLEEP=30

    pmodelhubpy-app:
        image: pmodelhubpy
        environment:
            - START_SLEEP=30

    popenpy-app:
        image: popenpy
        environment:
            - START_SLEEP=30

    pdemopy-app:
        image: pdemopy
        environment:
            - START_SLEEP=30

    pfacepy-app:
        image: pfacepy
        environment:
            - START_SLEEP=30

    ufacepy-app:
        image: ufacepy
        environment:
            - START_SLEEP=50

    gatewaypy-app:
        image: gatewaypy
        ports:
            - 8080:8080
        environment:
            - START_SLEEP=60

